"""
Django settings for EnergyForecast project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import django_heroku
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*tb29!vc9j*^ohzgoi$erdx*0185168ax4$myh@19=pep!ek=q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'homepage.apps.HomepageConfig',
    'forecastmodel',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'EnergyForecast.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EnergyForecast.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

#DATABASES = {
 #     'default': dj_database_url.config(default='postgres://uowphygvpqoypv:5f727c814c534cec6387e4287ccf05a23804ea8f99c8611a861379d45ac836d7@ec2-54-246-89-234.eu-west-1.compute.amazonaws.com:5432/daibgtr0a8s837')
      
       
#     #   dj_database_url.config()
# # #         # 'ENGINE': 'django.db.backends.sqlite3',         
#  #            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#              'ENGINE': 'django.db.backends.postgresql_psycopg2',
#             'NAME': 'mydb',
#              'USER': 'myuser',
# #             'USER': 'uowphygvpqoypv',
#             'PASSWORD': 'mypass',
# # #         'PASSWORD': '5f727c814c534cec6387e4287ccf05a23804ea8f99c8611a861379d45ac836d7',
#              'HOST': 'localhost',
# # #         'HOST': 'ec2-54-246-89-234.eu-west-1.compute.amazonaws.com'
#              'PORT': '5432',
      
  #}
#DATABASES['default'] = dj_database_url.config(conn_max_age=600, ssl_require=True)
#DATABASES = { 'default': dj_database_url.config() }
#DATABASES['default'] = dj_database_url.config(default='postgres://uowphygvpqoypv:5f727c814c534cec6387e4287ccf05a23804ea8f99c8611a861379d45ac836d7@ec2-54-246-89-234.eu-west-1.compute.amazonaws.com:5432/daibgtr0a8s837')

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

DATABASES = {
    'default' : {
        'ENGINE': 'django.db.backends.postgresql', 
        'NAME': 'Test',
        'USER': 'postgres',
        'PASSWORD': 'Phoenix2020',
        'HOST': 'database-energy.cozo80jzrft1.us-east-2.rds.amazonaws.com',
        'PORT': '5432',
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

django_heroku.settings(locals())