# Generated by Django 3.0.3 on 2020-03-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InductionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.PositiveIntegerField()),
                ('Date', models.DateField()),
                ('Hour', models.PositiveIntegerField(choices=[('0', 0), ('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6), ('7', 7), ('8', 8), ('9', 9), ('10', 10), ('11', 11), ('12', 12), ('13', 13), ('14', 14), ('15', 15), ('16', 16), ('17', 17), ('18', 18), ('19', 19), ('20', 20), ('21', 21), ('22', 22)])),
                ('Temp', models.IntegerField()),
                ('Demand', models.DecimalField(decimal_places=2, max_digits=5)),
                ('DayType', models.CharField(max_length=254)),
            ],
        ),
    ]
